import React from "react";
import "../../style/QuizPage.css";

const Question = props => {
  return (
    <>
      <div className="question">
        <strong>Q - </strong>{props.questionNumber}  {props.question.question
          .replace(/ /g, " ") // ANY OTHER WAY PLEASE ???
          .replace(/&#039;/g, "'") // STILL ISSUE WITH &#039;
          .replace(/&quot;/g, "\"")
          .replace(/&shy;/g, "-")
          .replace(/&rsquo;/g, "’")
          .replace(/&lsquo;/g, "‘")
          .replace(/&ldquo;/g, "“")
          .replace(/&rdquo;/g, "”")
          .replace(/&amp;/g, "&")
          .replace(/&Agrave;/g, "À")
          .replace(/&Aacute;/g, "Á")
          .replace(/&Acirc;/g, "Â")
          .replace(/&Atilde;/g, "Ã")
          .replace(/&Auml;/g, "Ä")
          .replace(/&Aring;/g, "Å")
          .replace(/&agrave;/g, "à")
          .replace(/&aacute;/g, "á")
          .replace(/&acirc;/g, "â")
          .replace(/&atilde;/g, "ã")
          .replace(/&auml;/g, "ä")
          .replace(/&aring;/g, "å")
          .replace(/&AElig;/g, "Æ")
          .replace(/&aelig;/g, "æ")
          .replace(/&szlig;/g, "ß")
          .replace(/&Ccedil;/g, "Ç")
          .replace(/&ccedil;/g, "ç")
          .replace(/&Egrave;/g, "È")
          .replace(/&Eacute;/g, "É")
          .replace(/&Ecirc;/g, "Ê")
          .replace(/&Euml;/g, "Ë")
          .replace(/&egrave;/g, "è")
          .replace(/&eacute;/g, "é")
          .replace(/&ecirc;/g, "ê")
          .replace(/&euml;/g, "ë")
          .replace(/&#131;/g, "ƒ")
          .replace(/&Igrave;/g, "Ì")
          .replace(/&Iacute;/g, "Í")
          .replace(/&Icirc;/g, "Î")
          .replace(/&Iuml;/g, "Ï")
          .replace(/&igrave;/g, "ì")
          .replace(/&iacute;/g, "í")
          .replace(/&icirc;/g, "î")
          .replace(/&iuml;/g, "ï")
          .replace(/&Ntilde;/g, "Ñ")
          .replace(/&ntilde;/g, "ñ")
          .replace(/&Ograve;/g, "Ò")
          .replace(/&Oacute;/g, "Ó")
          .replace(/&Ocirc;/g, "Ô")
          .replace(/&Otilde;/g, "Õ")
          .replace(/&Ouml;/g, "Ö")
          .replace(/&ograve;/g, "ò")
          .replace(/&oacute;/g, "ó")
          .replace(/&ocirc;/g, "ô")
          .replace(/&otilde;/g, "õ")
          .replace(/&ouml;/g, "ö")
          .replace(/&Oslash;/g, "Ø")
          .replace(/&oslash;/g, "ø")
          .replace(/&#140;/g, "Œ")
          .replace(/&#156;/g, "œ")
          .replace(/&#138;/g, "Š")
          .replace(/&#154;/g, "š")
          .replace(/&Ugrave;/g, "Ù")
          .replace(/&Uacute;/g, "Ú")
          .replace(/&Ucirc;/g, "Û")
          .replace(/&Uuml;/g, "Ü")
          .replace(/&ugrave;/g, "ù")
          .replace(/&uacute;/g, "ú")
          .replace(/&ucirc;/g, "û")
          .replace(/&uuml;/g, "ü")
          .replace(/&#181;/g, "µ")
          .replace(/&#215;/g, "×")
          .replace(/&Yacute;/g, "Ý")
          .replace(/&#159;/g, "Ÿ")
          .replace(/&yacute;/g, "ý")
          .replace(/&yuml;/g, "ÿ")
          .replace(/&#176;/g, "°")
          .replace(/&#134;/g, "†")
          .replace(/&#135;/g, "‡")
          .replace(/&lt;/g, "<")
          .replace(/&gt;/g, ">")
          .replace(/&#177;/g, "±")
          .replace(/&#171;/g, "«")
          .replace(/&#187;/g, "»")
          .replace(/&#191;/g, "¿")
          .replace(/&#161;/g, "¡")
          .replace(/&#183;/g, "·")
          .replace(/&#149;/g, "•")
          .replace(/&#153;/g, "™")
          .replace(/&copy;/g, "©")
          .replace(/&reg;/g, "®")
          .replace(/&#167;/g, "§")
          .replace(/&#182;/g, "¶")
        }
      </div>
    </>
  );
};

export default Question;